# Generated by Django 3.1 on 2020-08-04 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0002_auto_20200804_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(to='rest_api.Project'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
