# Generated by Django 3.1 on 2020-08-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20200804_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='p_name',
            new_name='project_name',
        ),
    ]
